apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: employee-app
        image: hemanathan18/employee-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
